### ISSUE TITLE
tracking: design polish

### ISSUE THREAD

**Issue by iuioiua** [denoland/saaskit#346]
It would be good to get a 2nd opinion on the design of some of these pages. Any suggestions would be welcome.
- [ ] [/](https://hunt.deno.land/) (item summary spacing can probably be improved)
- [ ] [/stats](https://hunt.deno.land/stats)
- [ ] [/blog](https://hunt.deno.land/blog)
- [ ] [/account](https://hunt.deno.land/account)
- [x] [/submit](https://hunt.deno.land/submit) (feels a bit empty)
- [x] [/user/:login](https://hunt.deno.land/user/iuioiua) (perhaps, the profile details could be more prominent)
- [x] [/pricing](https://hunt.deno.land/pricing)

Todo:
- #467
- #468
- #469

**Comment by brunocorrea23** [comment]
Adding to this here just two things that might make sense:
- #268 the last thing that lighthouse is complaining in order to get a perfect score is adjusting the size of the tap areas on mobile
- The links on the new pricing page are hard to see on dark mode:
<img width="338" alt="Screenshot 2023-07-05 at 20 39 11" src="https://github.com/denoland/saaskit/assets/8139585/6e4d3ec6-ebd6-4b5e-9e1b-8c23b8d5ba4b">

**Comment by hashrock** [comment]
These are just a suggestion, not a strong opinion.

# Overall / nav

- A little white space stands out, so it might be better to use the space loosely
- Add a little more space between the header and the main content.

# Root

- increase the spacing between each item
- Increase title font size for each item
- Added selected state to Last Week / Last Month / All time buttons (logically tab / radio buttons)
- Add buttons to pagination UI (I usually refer [tailwind UI](https://tailwindui.com/components/application-ui/navigation/pagination))
- upvote button should be implemented with button element (for accessibility, keyboard operation)

# /stats

- Maybe create a section to display numbers such as today's total visitors, weekly total visitors, etc

# /blog

- Increase font size of main content

# /item/:itemId

- Increase font size of title text etc
- maybe add a back link (you can go back by clicking the logo, but to clarify the relationship between collection view and single view)

# submit

feels a bit empty, but I can't think of a way to improve it since there's nothing to display.

**Comment by hashrock** [comment]
I'm not a big fan of this, but it can be used as an accent.

<img width="1094" alt="image" src="https://github.com/denoland/saaskit/assets/3132889/77c833e1-27b2-4aee-a11f-e02189aa0415">


![Frame 4](https://github.com/denoland/saaskit/assets/3132889/7ba4b827-bfd8-49b2-a8ed-8141dca54504)

**Comment by iuioiua** [comment]
These are all excellent points. Thanks, guys! I mostly agree with the suggestions.

**Comment by roberto-morado** [comment]
I would like to add my opinion on this. Deno's design has gradually improved to what is today, I personally love it and would like to see it reflected here as well. Here is an image of what I mean, I used screenshots from deno.land, dash.deno.land, and hunt.deno.land

<img width="1285" alt="Screenshot 2023-07-11 at 3 11 46 PM" src="https://github.com/denoland/saaskit/assets/122580309/9e6ee444-f8ad-4d38-ad57-67188050d072">

<img width="1285" alt="Screenshot 2023-07-11 at 3 11 46 PM" src="https://github.com/denoland/saaskit/assets/122580309/1f34950e-8445-49c2-92b7-06805a771e49">

**Comment by iuioiua** [comment]
Frankly, while SaaSKit takes inspiration from a few other Deno products, I'd like it to have its own flavour.

**Comment by roberto-morado** [comment]
Gotcha 👌

**Comment by iuioiua** [comment]
@hashrock, many design changes have been made. Is there anything else remaining that could do with improvement? I think the design looks good now.

**Comment by iuioiua** [comment]
Actually, one issue I have is that [x/tabler_icons](https://deno.land/x/tabler_icons_tsx), while great, doesn't have the official social icons. Is there another icons module that does?

**Comment by hashrock** [comment]
I think there is no remaining thing for me. good time to close this issue

**Comment by hashrock** [comment]
for branding icons, how about this
https://simpleicons.org/

**Comment by iuioiua** [comment]
Cool! I'll look into it!
