### ISSUE TITLE
todo: rewrite README

### ISSUE THREAD

**Issue by iuioiua** [denoland/saaskit#460]
Should include:
- [x] REST API reference
- [x] Deploying to Production with Docker
- [x] Design decision notes, where applicable
- [ ] Showcase related projects
- [ ] Release schedule

**Comment by iuioiua** [comment]
The release schedule still needs to be finalised. I'll add related projects in time. Closing this now.
