### ISSUE TITLE
todo: move `POST /submit` logic to `POST /items`

### ISSUE THREAD

**Issue by iuioiua** [denoland/saaskit#462]
Requirements:
- [x] Require the user to be signed in. E.g.: https://github.com/denoland/saaskit/blob/0f61d354a36d4f877c58feb162531d3cf087e5f7/routes/api/me/votes.ts#L12-L17
- [x] Change the form action to the new endpoint.
- [x] Test that the form works in correctly creating an item.
