### ISSUE TITLE
todo: add JSDoc examples to simple functions

### ISSUE THREAD

**Issue by iuioiua** [denoland/saaskit#492]
Most functions in `/utils` are simple functions that could do with a little documentation. Objectives:
1. Provide a short description of what the function does and/or its purpose.
2. Provide an `@example` snippet.
3. [Keep It Simple, Stupid (KISS)](https://www.interaction-design.org/literature/topics/keep-it-simple-stupid)
4. Link to relevant documentation, if needed.

Targets:
- [ ] `/utils/db.ts`
- [ ] `/utils/http.ts`
- [ ] `/utils/islands.ts`
- [ ] `/utils/payments.ts`
- [ ] `/utils/posts.ts`

**Comment by iuioiua** [comment]
Great! I think it'd be best if we tackled this in chunks - like one PR per file.

**Comment by Nkiriobasi** [comment]
Alright, that’s fine

**Comment by roberto-morado** [comment]
I see 👀 there are some functions still, I would like to work on this as well.

@iuioiua could you assign me to this?

**Comment by iuioiua** [comment]
Hi @roberto-morado, I realised it'd be best if I were the one to work on this one, given I know the context and nuances behind a lot of this functionality. I assigned myself to make this clear. Thanks anyway for offering!

**Comment by roberto-morado** [comment]
No problem 👍

**Comment by iuioiua** [comment]
This has been completed in a number of the related PRs.
