### ISSUE TITLE
Feature request: `<Meta />` component

### ISSUE THREAD

**Issue by iuioiua** [denoland/saaskit#55]
**Is your feature request related to a problem? Please describe.**
The blog, including the index and individual posts, has meta tags, which are a strong base for future meta tags support but are manually written.

**Describe the solution you'd like**
A `<Meta />` component that can be reused anywhere on the website.

**Additional context**
Spec:
- [ ] `<Meta />` component with reasonable defaults and properties such as `title`, `description`, etc.
- [ ] Comments sectioning meta tags by platform. For example, see [this](https://www.heymeta.com/url/www.youtube.com/watch?v=iuJDhFRDx9M) and click **Generate**.
- [ ] Add the new component wherever applicable on the website.
